### PR TITLE
Expose run function to execute simpleindex from another Python module.

### LINKED ISSUE #11: Execute simpleindex from another Python module
At the moment, `simpleindex` can be executed only as `python -m simpleindex ...`. It would be beneficial to embedded simpleindex into another Python application as a simple module.

### PR DESCRIPTION
**Pull request by tibortakacs**
This simple change enables embedding simpleindex into another Python module:

```python
from simpleindex import run
run(["/path/to/config.toml"])
```

Close #11.

### CODE REVIEW

File: src/simpleindex/__init__.py [hunk 1]
```diff
@@ -2,3 +2,5 @@
 """
 
 __version__ = "0.4.0"
+
+from .__main__ import run
```
Comment (uranusjr) [inline src/simpleindex/__init__.py:6]:
```suggestion
from .__main__ import run

```

File: src/simpleindex/__main__.py [hunk 2]
```diff
@@ -39,14 +40,15 @@ async def dist(request: Request):
     ]
 
 
-def main():
+def run(args: typing.List[str]):
+    print(args)
```
Comment (uranusjr) [inline src/simpleindex/__main__.py:44]:
```suggestion
def run(args: typing.Optional[typing.List[str]] = None):
```

File: src/simpleindex/__main__.py [hunk 3]
```diff
@@ -61,4 +63,4 @@ def main():
 
 
 if __name__ == "__main__":
-    main()
+    run(sys.argv[1:])
```
Comment (uranusjr) [inline src/simpleindex/__main__.py:66]:
```suggestion
    run()
```

**Comment by saaketp** [comment]
This breaks the console script entrypoint, which still refers to main function, which doesn't exist anymore.

https://github.com/uranusjr/simpleindex/blob/6717b73a289f8231834bd6f2df22677e10c9aa40/pyproject.toml#L29

After upgrading to 0.5.0 I get `ImportError: cannot import name 'main' from 'simpleindex.__main__'` when trying to run simpleindex.

**Comment by uranusjr** [comment]
Thanks for catching that 😓 

Would you be interested in submitting a fix for this?

**Comment by saaketp** [comment]
Ok, created a PR.
https://github.com/uranusjr/simpleindex/pull/13

Gave default value for run args and used that as entrypoint instead of main.
